apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${SERVICES_VIEWER_ROLE_NAME}
  namespace: ${NAMESPACE@microservice-config}
  labels:
    moduleid: microservice-home-realm
    version: 1.70.0-master
rules:
  - apiGroups: [""]
    resources: ["namespaces", "services", "pods"]
    verbs: ["get", "list"]
