apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${SERVICES_VIEWER_DEFAULT_BIND_NAME}
  namespace: ${NAMESPACE@microservice-config}
  labels:
    moduleid: microservice-home-realm
    version: 1.70.0-master
subjects:
- kind: ServiceAccount
  name: ${SERVICES_VIEWER_ACCOUNT_NAME}
  namespace: ${NAMESPACE@microservice-config}
roleRef:
  kind: Role
  name: ${SERVICES_VIEWER_ROLE_NAME}
  apiGroup: rbac.authorization.k8s.io
